<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Nallans-NewPC" name="com.JusDone.qa.TestCases.LoginPageTest" tests="8" failures="1" timestamp="06 Feb 2018 01:07:53 GMT" time="115.307" errors="0">
  <testcase name="verifyLoginNameTest" time="12.360" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="verifyLForgotPwdTest" time="13.922" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="verifyLoginBtnTest" time="13.237" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="verifyLRememberMeTest" time="12.505" classname="com.JusDone.qa.TestCases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.JusDone.qa.TestCases.LoginPageTest.verifyLRememberMeTest(LoginPageTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLRememberMeTest -->
  <testcase name="verifyLCreateAcctBtnTest" time="12.168" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="ValidLoginTest" time="22.372" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="InvalidLoginTest" time="15.819" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="BlankInputLoginTest" time="12.924" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
</testsuite> <!-- com.JusDone.qa.TestCases.LoginPageTest -->
