<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Nallans-NewPC" name="com.JusDone.qa.TestCases.LoginPageTest" tests="8" failures="1" timestamp="16 Feb 2018 20:32:34 GMT" time="131.091" errors="0">
  <testcase name="verifyLoginNameTest" time="12.705" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="verifyLForgotPwdTest" time="14.951" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="verifyLoginBtnTest" time="13.913" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="verifyLRememberMeTest" time="16.686" classname="com.JusDone.qa.TestCases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.JusDone.qa.TestCases.LoginPageTest.verifyLRememberMeTest(LoginPageTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- verifyLRememberMeTest -->
  <testcase name="verifyLCreateAcctBtnTest" time="13.710" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="ValidLoginTest" time="23.214" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="InvalidLoginTest" time="21.068" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
  <testcase name="BlankInputLoginTest" time="14.844" classname="com.JusDone.qa.TestCases.LoginPageTest"/>
</testsuite> <!-- com.JusDone.qa.TestCases.LoginPageTest -->
